//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityUrInterfaces
{
    [Serializable]
    public class UrJointsMsg : Message
    {
        public const string k_RosMessageName = "unity_ur_interfaces/UrJoints";
        public override string RosMessageName => k_RosMessageName;

        public double[] degrees;

        public UrJointsMsg()
        {
            this.degrees = new double[0];
        }

        public UrJointsMsg(double[] degrees)
        {
            this.degrees = degrees;
        }

        public static UrJointsMsg Deserialize(MessageDeserializer deserializer) => new UrJointsMsg(deserializer);

        private UrJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.degrees, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.degrees);
            serializer.Write(this.degrees);
        }

        public override string ToString()
        {
            return "UrJointsMsg: " +
            "\ndegrees: " + System.String.Join(", ", degrees.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
