//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityUrPkg
{
    [Serializable]
    public class UrJointsMsg : Message
    {
        public const string k_RosMessageName = "unity_ur_pkg_msgs/UrJoints";
        public override string RosMessageName => k_RosMessageName;

        public double[] position;

        public UrJointsMsg()
        {
            this.position = new double[0];
        }

        public UrJointsMsg(double[] position)
        {
            this.position = position;
        }

        public static UrJointsMsg Deserialize(MessageDeserializer deserializer) => new UrJointsMsg(deserializer);

        private UrJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "UrJointsMsg: " +
            "\nposition: " + System.String.Join(", ", position.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
